### ISSUE TITLE
UI code for Marketing Campaign App has bug described below

### ISSUE THREAD

**Issue by sweanan** [PacktPublishing/LangChain-MasterClass---Build-15-OpenAI-and-LLAMA-2-LLM-Apps-using-Python#4]
**BUG:**

**Reproduce steps:**

/LangChain-MasterClass---Build-15-OpenAI-and-LLAMA-2-LLM-Apps-using-Python/S09 - Project 4 - Marketing Campaign App/Marketing Campaign App - Project Source Code/Project 4 - Final Code/app.py

when running the above code for option "Senior Citizen", the UI fails with the below error as it has TYPO for 'senior Citizen' ---> 'Senior Citizen'

`File "LangChain-MasterClass---Build-15-OpenAI-and-LLAMA-2-LLM-Apps-using-Python/.venv/lib/python3.10/site-packages/streamlit/runtime/scriptrunner/script_runner.py", line 535, in _run_script
    exec(code, module.__dict__)
File "LangChain-MasterClass---Build-15-OpenAI-and-LLAMA-2-LLM-Apps-using-Python/S09 - Project 4 - Marketing Campaign App/Marketing Campaign App - Project Source Code/Project 4 - Final Code/app.py", line 158, in <module>
    st.write(getLLMResponse(form_input,age_option,tasktype_option))
File "LangChain-MasterClass---Build-15-OpenAI-and-LLAMA-2-LLM-Apps-using-Python/S09 - Project 4 - Marketing Campaign App/Marketing Campaign App - Project Source Code/Project 4 - Final Code/app.py", line 113, in getLLMResponse
    examples=examples,`

[PR](https://github.com/PacktPublishing/LangChain-MasterClass---Build-15-OpenAI-and-LLAMA-2-LLM-Apps-using-Python/pull/3) Created to fix the above issue

**Comment by Sonakshis** [comment]
Hi @sweanan 
Thank you so much for bringing this to our attention. We have updated the code bundle for this course.
Link to updated code bundle: 
https://github.com/PacktPublishing/LangChain-Masterclass---Build-15-OpenAI-and-LLAMA-2-LLM-Apps-Using-Python-
Happy learning!

**Comment by sweanan** [comment]
Thanks @Sonakshis CC: @robcamer
