### ISSUE TITLE
many of the langchain functions are deprecated

### ISSUE THREAD

**Issue by alexmlopez** [PacktPublishing/LangChain-MasterClass---Build-15-OpenAI-and-LLAMA-2-LLM-Apps-using-Python#5]
# Deprecated
from langchain.chat_models import ChatOpenAI

#Correction
from langchain_openai import ChatOpenAI

Code Errors

/usr/local/lib/python3.10/site-packages/langchain_core/_api/deprecation.py:117: LangChainDeprecationWarning: The function `__call__` was deprecated in LangChain 0.1.7 and will be removed in 0.2.0. Use invoke instead.
  warn_deprecated(
  
  
install -U langchain-openai` and import as `from langchain_openai import OpenAI`.   
   
The class `langchain_community.llms.huggingface_hub.HuggingFaceHub` was deprecated in langchain-community 0.0.21 and will be removed in 0.2.0. Use HuggingFaceEndpoint instead.
  warn_deprecated(

**Comment by Sonakshis** [comment]
Hi @alexmlopez 
Thank you so much for bringing this to our attention. We have updated the code bundle for this course.
Link to updated code bundle: 
https://github.com/PacktPublishing/LangChain-Masterclass---Build-15-OpenAI-and-LLAMA-2-LLM-Apps-Using-Python-
Happy learning!
